-- CTRL + / 빠른 주석

SELECT * FROM EMPLOYEES;
SELECT * FROM DEPARTMENTS;
SELECT * FROM LOCATIONS;
SELECT * FROM JOBS;
-- 특정 컬럼만 조회 하려면, 나열
SELECT EMPLOYEE_ID, FIRST_NAME, PHONE_NUMBER FROM EMPLOYEES;
-- 문자, 날자는 왼쪽으로 표시, 숫자는 오른족에 나타난다.
SELECT FIRST_NAME, HIRE_DATE, SALARY, COMMISSION_PCT, FROM EMPLOYEES;
-- 숫자 컬럼은 * / + - 가 된다.
SELECT FIRST_NAME, SALARY, SALARY + SALARY * 0.1 FROM EMPLOYEES;
-- 컬럼 별칭 ALIAS
SELECT FIRST_NAME AS 이름, SALARY 급여, SALARY + SALARY * 0.1 AS "최종 급여" FROM EMPLOYEES;
-- 문자열 붙이기 ||
SELECT FIRST_NAME || '''님의 급여는' || '$ 입니다' AS SALARY FROM EMPLOYEES;
-- DISCTINT
SELECT  DISTINCT DEPARTMENT_ID FROM EMPLOYEES;
SELECT DISTINCT FIRST_NAME, DEPARTMENT_ID FROM EMPLOYEES; --조회된 데이터 기준으로 중복을 제거
--ROWID(데이터 주소), ROWNUM(데이터가 조회된 순서)
SELECT EMPLOYEE_ID, FIRST_NAME, ROWID, ROWNUM FROM EMPLOYEES;