-- WHERE절

SELECT * FROM EMPLOYEES;

SELECT FIRST_NAME, JOB_ID FROM EMPLOYEES WHERE JOB_ID = 'IT_PROG';
SELECT * FROM EMPLOYEES WHERE SALARY >= 15000;
SELECT * FROM EMPLOYEES WHERE SALARY <= 10000;
SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID <> 50; --같지 않음
SELECT * FROM EMPLOYEES WHERE FIRST_NAME = 'Steven'; -- 데이터는 대소문자 구분한다
SELECT * FROM EMPLOYEES WHERE HIRE_DATE = '04/01/30'; -- 날짜도 문자열로 찾으면 된다
SELECT * FROM EMPLOYEES WHERE HIRE_DATE <= '04/01/30';

--BETWEEN A AND B (이상 ~이하)
SELECT * FROM EMPLOYEES WHERE SALARY BETWEEN 10000 AND 15000;
SELECT * FROM EMPLOYEES WHERE HIRE_DATE BETWEEN '03/01/01' AND '03/12/31';