--집합연산자
--UNION 합집합 중복X
--UNION ALL 합집합 중복O
--INTERSECT 교집합
--MINUS 차집합

--컬럼 갯수가 일치해야만 집합 연산자 사용이 가능하다
--집합연사자를 사용할 경우 앞의 SELECT문 마지막의 ;을 지워줘야 정상적으로 작동한다.

--합집합 중복 X
SELECT FIRST_NAME, HIRE_DATE FROM EMPLOYEES WHERE HIRE_DATE LIKE '04%'
UNION
SELECT FIRST_NAME, HIRE_DATE FROM EMPLOYEES WHERE DEPARTMENT_ID = 20;

--합집합 중복 O
SELECT FIRST_NAME, HIRE_DATE FROM EMPLOYEES WHERE HIRE_DATE LIKE '04%'
UNION ALL
SELECT FIRST_NAME, HIRE_DATE FROM EMPLOYEES WHERE DEPARTMENT_ID = 20;

--교집합
SELECT FIRST_NAME, HIRE_DATE FROM EMPLOYEES WHERE HIRE_DATE LIKE '04%'
INTERSECT
SELECT FIRST_NAME, HIRE_DATE FROM EMPLOYEES WHERE DEPARTMENT_ID = 20;

--차집합 (집합 연산 후 남아 있는 값 중에서 중복되는 값이 있으면 중복만 제거한다 / 3,3이 남아 있는 경우 3만 남게 된다)
SELECT FIRST_NAME, HIRE_DATE FROM EMPLOYEES WH HIRE_DATE LIKE '04%'
MINUS
SELECT FIRST_NAME, HIRE_DATE FROM EMPLOYEES WHERE DEPARTMENT_ID = 20;

--가상 테이블을 합쳐서 사용할 수 있다.
SELECT 'PARK', 200 FROM DUAL
UNION ALL
SELECT 'KIM', 300 FROM DUAL
UNION ALL
SELECT 'CHOI', 400 FROM DUAL;





