CREATE TABLE MEMBERS (
    MNO NUMBER(5) PRIMARY KEY,
    NAME VARCHAR2(30) NOT NULL,
    ADDRESS VARCHAR2(5),
    REGDATE DATE DEFAULT SYSDATE
                    );
                    
CREATE SEQUENCE MEMBERS_SEQ NOCACHE;

SELECT * FROM MEMBERS;

ALTER TABLE MEMBERS MODIFY ADDRESS VARCHAR2(50);

INSERT INTO MEMBERS VALUES(1, '박인욱', '붓싼', SYSDATE);

SELECT * FROM MEMBERS WHERE MNO IN(1);

COMMIT;

SELECT * FROM EMPLOYEES;
SELECT * FROM DEPARTMENTS;

SELECT FIRST_NAME, SALARY, E.DEPARTMENT_ID, DEPARTMENT_NAME
FROM EMPLOYEES E
LEFT JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
WHERE EMPLOYEE_ID = 120;
